//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMSApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShiftWorker
    {
        public int ShiftWorkerId { get; set; }
        public Nullable<int> ShiftId { get; set; }
        public Nullable<int> WorkerId { get; set; }
        public Nullable<bool> IsOrgApproved { get; set; }
        public Nullable<bool> IsWorkerApproved { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual User User { get; set; }
        public virtual VolunteerShift VolunteerShift { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
