//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMSApp.Models
{
    using System;
    
    public partial class spValidateUserResult
    {
        public Nullable<System.Guid> TokenResult { get; set; }
        public Nullable<int> UserId { get; set; }
    }
}
