//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMSApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public Status()
        {
            this.VolunteerOrganizations = new HashSet<VolunteerOrganization>();
            this.Workers = new HashSet<Worker>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<VolunteerOrganization> VolunteerOrganizations { get; set; }
        public virtual ICollection<Worker> Workers { get; set; }
    }
}
