//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMSApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Admins = new HashSet<Admin>();
            this.ShiftWorkers = new HashSet<ShiftWorker>();
            this.VolunteerOrganizations = new HashSet<VolunteerOrganization>();
            this.Workers = new HashSet<Worker>();
            this.UserLogins = new HashSet<UserLogin>();
        }
    
        public int Id { get; set; }
        public Nullable<int> UserType { get; set; }
        public string EmailId { get; set; }
        public string Password { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public string PinCode { get; set; }
    
        public virtual ICollection<Admin> Admins { get; set; }
        public virtual ICollection<ShiftWorker> ShiftWorkers { get; set; }
        public virtual usertype usertype1 { get; set; }
        public virtual ICollection<VolunteerOrganization> VolunteerOrganizations { get; set; }
        public virtual ICollection<Worker> Workers { get; set; }
        public virtual ICollection<UserLogin> UserLogins { get; set; }
    }
}
