//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMSApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLogin
    {
        public System.Guid AuthToken { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> LoginTimeStamp { get; set; }
        public Nullable<System.DateTime> AuthTokenValidStart { get; set; }
        public Nullable<System.DateTime> AuthTokenValidEnd { get; set; }
        public Nullable<bool> IsLoggedOut { get; set; }
        public Nullable<System.DateTime> LogOutTimeStamp { get; set; }
    
        public virtual User User { get; set; }
    }
}
