//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMSApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbVMSEntities : DbContext
    {
        public DbVMSEntities()
            : base("name=DbVMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admin> Admins { get; set; }
        public DbSet<ShiftWorker> ShiftWorkers { get; set; }
        public DbSet<Status> Status { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<usertype> usertypes { get; set; }
        public DbSet<VolunteerActivity> VolunteerActivities { get; set; }
        public DbSet<VolunteerActivityJob> VolunteerActivityJobs { get; set; }
        public DbSet<VolunteerOrganization> VolunteerOrganizations { get; set; }
        public DbSet<VolunteerShift> VolunteerShifts { get; set; }
        public DbSet<Worker> Workers { get; set; }
    }
}
