//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMSApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VolunteerActivityJob
    {
        public VolunteerActivityJob()
        {
            this.VolunteerShifts = new HashSet<VolunteerShift>();
        }
    
        public int JobId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> ActivityId { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string City { get; set; }
    
        public virtual VolunteerActivity VolunteerActivity { get; set; }
        public virtual ICollection<VolunteerShift> VolunteerShifts { get; set; }
    }
}
