//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMSApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VolunteerOrganization
    {
        public VolunteerOrganization()
        {
            this.VolunteerActivities = new HashSet<VolunteerActivity>();
        }
    
        public int OrgId { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string EmailId { get; set; }
        public string Password { get; set; }
        public string Address { get; set; }
        public string Description { get; set; }
        public string Website { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual Status Status1 { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<VolunteerActivity> VolunteerActivities { get; set; }
    }
}
